baseURL = "https://lucven.com/"
languageCode = "en-us"
title = "Lucven AI Systems"
theme = "PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"]  # Enables local search

[pagination]
  pagerSize = 10

[author]
  name = "Lakshay Chhabra"
  homepage = "https://lucven.com"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  env = "production"
  description = "Exploring Retrieval-Augmented Generation (RAG), Machine Learning systems, and scalable AI infra."
  author = "Lakshay Chhabra"
  defaultTheme = "dark"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowSearch = true  # 🔥 Enables Fuse.js search
  ShowToc = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  disableSpecial1stPost = false
  displayFullLangName = true
  
  [params.comments]
    enabled = true
    provider = "giscus"


  [params.assets]
    favicon = "favicon_io/favicon.ico"
    disableFingerprinting = false

  [params.opengraph]
    image = "images/og-image.png"

  [params.profileMode]
    enabled = false
    title = "Lakshay Chhabra"
    subtitle = "ML Engineer | RAG Specialist | AI Infra"
    imageUrl = "images/dp.png"
    imageTitle = "Lucven Logo"
    buttons = [
      { name = "Articles", url = "/posts" },
      { name = "Tags", url = "/tags" },
      { name = "Categories", url = "/categories" },
      { name = "Archives", url = "/archives" },
      { name = "Search", url = "/search" },
    ]

  [params.analytics]
    googleAnalyticsID = ""

  [params.meta]
    keywords = ["AI", "Machine Learning", "RAG", "LLMs", "AI Infra", "Quant Trading", "Lakshay Chhabra"]

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/lakshaychhabra"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/lakshaychhabra123"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 3

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 4

[[menu.main]]
  name = "Archives"
  url = "/archives/"
  weight = 5

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 6

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true




[giscus]
  repo = "lakshaychhabra/lucven-comments"
  repoID = "R_kgDOPYOEYw"
  category = "Q&A"
  categoryID = "DIC_kwDOPYOEY84CtxWt"
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "top"
  theme = "preferred_color_scheme"
  lang = "en"
  loading = "lazy"